### ISSUE TITLE
Support pathes as outfile

### ISSUE THREAD

**Issue by lezsakdomi** [nonnymoose/xsr#27] opened 2017-10-08 18:59 UTC
It could be very annoying, when you debug, why `xsr /tmp/record.html` don't work.

**Comment by lezsakdomi** [comment] 2017-10-08 19:05
Alternative: `xsr /dev/stdout`

**Comment by nonnymoose** [comment] 2017-10-08 22:08
Wow, that was a big bug.

**Comment by lezsakdomi** [comment] 2017-10-08 22:16
I suggest you using absolute pathes only

**Comment by lezsakdomi** [comment] 2017-10-08 22:39
Still leaves a bit trash in the current directory.

An empty file called `$(basename $outfile)`

Hotfix:
```
xsr $path/$file.html
xdg-open $path/$file.html
sleep 3; rm $file.html
```

**Comment by nonnymoose** [comment] 2017-10-08 22:42
@lezsakdomi Oddly enough, I cannot reproduce this. What was the path of your current directory?

**Comment by lezsakdomi** [comment] 2017-10-08 22:56
`/home/led/Downloads/xsr`
But so I still experiment with it.
The release was fine 😠

**Comment by lezsakdomi** [comment] 2017-10-08 23:00
Exact behavior:
It places an empty file (with the basename of the outfile) in the current directory, which could overwrite the regular outfile if that's path corresponds to `.`

**Comment by nonnymoose** [comment] 2017-10-09 01:19
@lezsakdomi Did you press Ctrl+C to stop it?

**Comment by lezsakdomi** [comment] 2017-10-09 05:32
Yes. The Break doesn't work for me

**Comment by lezsakdomi** [comment] 2017-10-09 05:33
It was working fine in the release

**Comment by lezsakdomi** [comment] 2017-10-09 05:43
Possible duplicate of #22

**Comment by lezsakdomi** [comment] 2017-10-09 07:56
@nonnymoose  Why do you even use `$outfilename`? As I see, it's just a possible error-source, so I think, that this issue coul be solved by hardcoding "encoded_output.html" rather than getting the file name from user.

BTW it isn't escaped

**Comment by lezsakdomi** [comment] 2017-10-09 12:15
@nonnymoose Wow, it looks like `finish()` runs twice for me. The problem isn't with pathes :)

**Comment by lezsakdomi** [comment] 2017-10-09 12:40
```

Loading DB routines from perl5db.pl version 1.49_05
Editor support available.

Enter h or 'h h' for help, or 'man perldebug' for more help.

main::(./xsr:11):       $outfile = "Untitled Recording.html";
  DB<1> 

  DB<1> 

  DB<1> h
List/search source lines:               Control script execution:
  l [ln|sub]  List source code            T           Stack trace
  - or .      List previous/current line  s [expr]    Single step [in expr]
  v [line]    View around line            n [expr]    Next, steps over subs
  f filename  View source in file         <CR/Enter>  Repeat last n or s
  /pattern/ ?patt?   Search forw/backw    r           Return from subroutine
  M           Show module versions        c [ln|sub]  Continue until position
Debugger controls:                        L           List break/watch/actions
  o [...]     Set debugger options        t [n] [expr] Toggle trace [max depth] ][trace expr]
  <[<]|{[{]|>[>] [cmd] Do pre/post-prompt b [ln|event|sub] [cnd] Set breakpoint
  ! [N|pat]   Redo a previous command     B ln|*      Delete a/all breakpoints
  H [-num]    Display last num commands   a [ln] cmd  Do cmd before line
  = [a val]   Define/list an alias        A ln|*      Delete a/all actions
  h [db_cmd]  Get help on command         w expr      Add a watch expression
  h h         Complete help page          W expr|*    Delete a/all watch exprs
  |[|]db_cmd  Send output to pager        ![!] syscmd Run cmd in a subprocess
  q or ^D     Quit                        R           Attempt a restart
Data Examination:     expr     Execute perl code, also see: s,n,t expr
  x|m expr       Evals expr in list context, dumps the result or lists methods.
  p expr         Print expression (uses script's current package).
  S [[!]pat]     List subroutine names [not] matching pattern
  V [Pk [Vars]]  List Variables in Package.  Vars can be ~pattern or !pattern.
  X [Vars]       Same as "V current_package [Vars]".  i class inheritance tree.
  y [n [Vars]]   List lexicals in higher scope <n>.  Vars same as V.
  e     Display thread id     E Display all thread ids.
For more help, type h cmd_letter, or run man perldebug for all docs.
  DB<1> n
main::(./xsr:12):       $verbose = 0;
  DB<1> n
main::(./xsr:13):       $editimages = 0;
  DB<1> n
main::(./xsr:14):       $imgext="jpg";
  DB<1> n
main::(./xsr:15):       $focusedcap = 0;
  DB<1> n
main::(./xsr:16):       $countdown = 5;
  DB<1> n
main::(./xsr:17):       $screeni = 0; # counter for screenshot number
  DB<1> n
main::(./xsr:18):       $nomouse = 0;
  DB<1> n
main::(./xsr:19):       $helprequested = 0; # --help specified
  DB<1> n
main::(./xsr:47):               "no-mouse" => \$nomouse,
main::(./xsr:48):               "help|h" => \$helprequested
main::(./xsr:49):               ) or die "$!\n" . usage();
  DB<1> n
main::(./xsr:51):       if ($helprequested) {
  DB<1> n
main::(./xsr:56):       if (@ARGV == 1) {
  DB<1> n
main::(./xsr:57):               $outfile = $ARGV[0];
  DB<1> n
main::(./xsr:67):       $outfilename = $outfile;
  DB<1> n
main::(./xsr:68):       $outfilename =~ s/^.*\///;
  DB<1> n
main::(./xsr:69):       $outfilename_noext = $outfilename;
  DB<1> n
main::(./xsr:70):       $outfilename_noext =~ s/\.[^\.]*$//;
  DB<1> n
main::(./xsr:72):       if ($imgext == "png") {$mimetype = "image/png"}
  DB<1> n
main::(./xsr:72):       if ($imgext == "png") {$mimetype = "image/png"}
  DB<1> n
main::(./xsr:77):       $originaldir = cwd;
  DB<1> n
main::(./xsr:78):       $tmpdir = `mktemp -d`;
  DB<1> n
main::(./xsr:79):       chomp   $tmpdir; # mktemp returns a newline
  DB<1> n
main::(./xsr:80):       chdir $tmpdir or die "$! Is /tmp mounted?\n";
  DB<1> n
main::(./xsr:83):       $xdotool = `which xdotool`;
  DB<1> n
main::(./xsr:84):       chomp($xdotool);
  DB<1> n
main::(./xsr:85):       if ($nomouse) {$xdotool = "";}
  DB<1> n
main::(./xsr:86):       else {$xdotool or warn "xdotool unavailable: mouse cursor will not appear in screenshots\n";}
  DB<1> n
main::(./xsr:87):       $composite = `which composite`;
  DB<1> n
main::(./xsr:88):       chomp($composite);
  DB<1> n
main::(./xsr:89):       $composite or warn "composite unavailable: mouse cursor will not appear in screenshots\n";
  DB<1> n
main::(./xsr:90):       $scrot = `which scrot`;
  DB<1> n
main::(./xsr:91):       chomp($scrot);
  DB<1> n
main::(./xsr:92):       $scrot or die "scrot unavailable: cannot take screenshots\n";
  DB<1> n
main::(./xsr:160):      if ($countdown) {
  DB<1> n
main::(./xsr:172):      open "X", "-|", "xmodmap -pke"; # open keymap
  DB<1> n
main::(./xsr:173):      while (<X>) {
  DB<1> n
main::(./xsr:174):              if (/^keycode\s+(\d+) = (\w+)(?:\s+(\w+))?/) { # keycode <number> = <normal> <shift> ...
  DB<1> n
main::(./xsr:174):              if (/^keycode\s+(\d+) = (\w+)(?:\s+(\w+))?/) { # keycode <number> = <normal> <shift> ...
  DB<1> n
main::(./xsr:175):                      $k{$1}=$2; # store normal in k, a hash
  DB<1> n
main::(./xsr:176):                      $K{$1}=$3 if $3; # store shift in K, a hash
  DB<1> n
main::(./xsr:174):              if (/^keycode\s+(\d+) = (\w+)(?:\s+(\w+))?/) { # keycode <number> = <normal> <shift> ...
  DB<1> n
main::(./xsr:175):                      $k{$1}=$2; # store normal in k, a hash
  DB<1> n
main::(./xsr:176):                      $K{$1}=$3 if $3; # store shift in K, a hash
  DB<1> n
main::(./xsr:174):              if (/^keycode\s+(\d+) = (\w+)(?:\s+(\w+))?/) { # keycode <number> = <normal> <shift> ...
  DB<1> n
main::(./xsr:175):                      $k{$1}=$2; # store normal in k, a hash
  DB<1> n
main::(./xsr:176):                      $K{$1}=$3 if $3; # store shift in K, a hash
  DB<1> n
main::(./xsr:174):              if (/^keycode\s+(\d+) = (\w+)(?:\s+(\w+))?/) { # keycode <number> = <normal> <shift> ...
  DB<1> n
main::(./xsr:175):                      $k{$1}=$2; # store normal in k, a hash
  DB<1> 
main::(./xsr:176):                      $K{$1}=$3 if $3; # store shift in K, a hash
  DB<1> n
main::(./xsr:174):              if (/^keycode\s+(\d+) = (\w+)(?:\s+(\w+))?/) { # keycode <number> = <normal> <shift> ...
  DB<1> h
List/search source lines:               Control script execution:
  l [ln|sub]  List source code            T           Stack trace
  - or .      List previous/current line  s [expr]    Single step [in expr]
  v [line]    View around line            n [expr]    Next, steps over subs
  f filename  View source in file         <CR/Enter>  Repeat last n or s
  /pattern/ ?patt?   Search forw/backw    r           Return from subroutine
  M           Show module versions        c [ln|sub]  Continue until position
Debugger controls:                        L           List break/watch/actions
  o [...]     Set debugger options        t [n] [expr] Toggle trace [max depth] ][trace expr]
  <[<]|{[{]|>[>] [cmd] Do pre/post-prompt b [ln|event|sub] [cnd] Set breakpoint
  ! [N|pat]   Redo a previous command     B ln|*      Delete a/all breakpoints
  H [-num]    Display last num commands   a [ln] cmd  Do cmd before line
  = [a val]   Define/list an alias        A ln|*      Delete a/all actions
  h [db_cmd]  Get help on command         w expr      Add a watch expression
  h h         Complete help page          W expr|*    Delete a/all watch exprs
  |[|]db_cmd  Send output to pager        ![!] syscmd Run cmd in a subprocess
  q or ^D     Quit                        R           Attempt a restart
Data Examination:     expr     Execute perl code, also see: s,n,t expr
  x|m expr       Evals expr in list context, dumps the result or lists methods.
  p expr         Print expression (uses script's current package).
  S [[!]pat]     List subroutine names [not] matching pattern
  V [Pk [Vars]]  List Variables in Package.  Vars can be ~pattern or !pattern.
  X [Vars]       Same as "V current_package [Vars]".  i class inheritance tree.
  y [n [Vars]]   List lexicals in higher scope <n>.  Vars same as V.
  e     Display thread id     E Display all thread ids.
For more help, type h cmd_letter, or run man perldebug for all docs.
  DB<1> c 345
Line 345 not breakable.
  DB<2> c finish
^Cmain::finish(./xsr:104):              print STDOUT "\n";
  DB<3> n

main::finish(./xsr:105):                print STDERR "Current working dir: ".cwd()." (#".__LINE__.")";
  DB<3> n
Current working dir: /tmp/tmp.MQY0jdktI8 (#105)main::finish(./xsr:106):         if (FOUT) {
  DB<3> n
main::finish(./xsr:107):                        handletypingstate();
  DB<3> n
main::finish(./xsr:108):                        print <<"/html";
main::finish(./xsr:109):                        <div class="footer">
main::finish(./xsr:110):                                <i>Made using <a href="https://github.com/nonnymoose/xsr">X Steps Recorder</a>.</i>
main::finish(./xsr:111):                        </div>
main::finish(./xsr:112):                </body>
main::finish(./xsr:113):        </html>
main::finish(./xsr:114):        /html
  DB<3> n
main::finish(./xsr:116):                        FOUT->flush();
  DB<3> n
main::finish(./xsr:117):                        close FOUT;
  DB<3> n
main::finish(./xsr:118):                        close XIN;
  DB<3> n
main::finish(./xsr:120):                        if ($xdotool && $composite) {
  DB<3> n
main::finish(./xsr:121):                                open "MOUSEIN", "<", "mousegrabs" or warn "Couldn't open mousegrabs: mouse will not appear in screenshots\n";
  DB<3> n
Couldn't open mousegrabs: mouse will not appear in screenshots
 at ./xsr line 121.
        main::finish("INT") called at ./xsr line 240
        eval {...} called at ./xsr line 240
main::finish(./xsr:122):                                for ($i = 0; $i < $screeni; $i++) {
  DB<3> n
main::finish(./xsr:131):                                close "MOUSEIN";
  DB<3> n
main::finish(./xsr:135):                        if ($editimages) {
  DB<3> n
main::finish(./xsr:143):                        open "ASSOCFILE", "<", "tmpassoconly.html"; # this file contains only image associations, not base64
  DB<3> n
main::finish(./xsr:144):                        open "FINALFILE", ">", "tmpencoded.html"; # this file will contain base64
  DB<3> n
main::finish(./xsr:145):                        print STDERR "Current working dir: ".cwd()." (#".__LINE__.")";
  DB<3> n
Current working dir: /tmp/tmp.MQY0jdktI8 (#145)main::finish(./xsr:146):                 select FINALFILE;
  DB<3> n
main::finish(./xsr:147):                        while (<ASSOCFILE>) {
  DB<3> n
main::finish(./xsr:148):                                $_ =~ s/<img src=\"([^\"]+)\" \/>/"<img src=\"data:$mimetype;base64," . convertToB64($1) . "\" \/>"/gie; # replace <img> tags' src attr with a base64 uri
  DB<3> n
main::finish(./xsr:149):                                print $_;
  DB<3> n
main::finish(./xsr:148):                                $_ =~ s/<img src=\"([^\"]+)\" \/>/"<img src=\"data:$mimetype;base64," . convertToB64($1) . "\" \/>"/gie; # replace <img> tags' src attr with a base64 uri
  DB<3> n
main::finish(./xsr:149):                                print $_;
  DB<3> n
main::finish(./xsr:148):                                $_ =~ s/<img src=\"([^\"]+)\" \/>/"<img src=\"data:$mimetype;base64," . convertToB64($1) . "\" \/>"/gie; # replace <img> tags' src attr with a base64 uri
  DB<3> n
main::finish(./xsr:149):                                print $_;
  DB<3> n
main::finish(./xsr:148):                                $_ =~ s/<img src=\"([^\"]+)\" \/>/"<img src=\"data:$mimetype;base64," . convertToB64($1) . "\" \/>"/gie; # replace <img> tags' src attr with a base64 uri
  DB<3> n
main::finish(./xsr:149):                                print $_;
  DB<3> n
main::finish(./xsr:148):                                $_ =~ s/<img src=\"([^\"]+)\" \/>/"<img src=\"data:$mimetype;base64," . convertToB64($1) . "\" \/>"/gie; # replace <img> tags' src attr with a base64 uri
  DB<3> n
main::finish(./xsr:149):                                print $_;
  DB<3> c 150
Line 150 not breakable.
  DB<4> c 151
main::finish(./xsr:151):                        close ASSOCFILE;
  DB<5> n
main::finish(./xsr:152):                        close FINALFILE;
  DB<5> n
main::finish(./xsr:153):                        chdir $originaldir;
  DB<5> n
main::finish(./xsr:154):                        copy "$tmpdir/tmpencoded.html", $outfile; # put the output in the original directory
  DB<5> n
main::finish(./xsr:155):                        remove_tree $tmpdir;
  DB<5> n
main::finish(./xsr:157):                print STDOUT "\n";
  DB<5> n

main::(./xsr:341):      print STDERR "Current working dir: ".cwd()." (#".__LINE__.")";
  DB<5> n
Current working dir: /home/led/Letöltések/xsr (#341)main::(./xsr:342):  finish();
  DB<5> h
List/search source lines:               Control script execution:
  l [ln|sub]  List source code            T           Stack trace
  - or .      List previous/current line  s [expr]    Single step [in expr]
  v [line]    View around line            n [expr]    Next, steps over subs
  f filename  View source in file         <CR/Enter>  Repeat last n or s
  /pattern/ ?patt?   Search forw/backw    r           Return from subroutine
  M           Show module versions        c [ln|sub]  Continue until position
Debugger controls:                        L           List break/watch/actions
  o [...]     Set debugger options        t [n] [expr] Toggle trace [max depth] ][trace expr]
  <[<]|{[{]|>[>] [cmd] Do pre/post-prompt b [ln|event|sub] [cnd] Set breakpoint
  ! [N|pat]   Redo a previous command     B ln|*      Delete a/all breakpoints
  H [-num]    Display last num commands   a [ln] cmd  Do cmd before line
  = [a val]   Define/list an alias        A ln|*      Delete a/all actions
  h [db_cmd]  Get help on command         w expr      Add a watch expression
  h h         Complete help page          W expr|*    Delete a/all watch exprs
  |[|]db_cmd  Send output to pager        ![!] syscmd Run cmd in a subprocess
  q or ^D     Quit                        R           Attempt a restart
Data Examination:     expr     Execute perl code, also see: s,n,t expr
  x|m expr       Evals expr in list context, dumps the result or lists methods.
  p expr         Print expression (uses script's current package).
  S [[!]pat]     List subroutine names [not] matching pattern
  V [Pk [Vars]]  List Variables in Package.  Vars can be ~pattern or !pattern.
  X [Vars]       Same as "V current_package [Vars]".  i class inheritance tree.
  y [n [Vars]]   List lexicals in higher scope <n>.  Vars same as V.
  e     Display thread id     E Display all thread ids.
For more help, type h cmd_letter, or run man perldebug for all docs.
  DB<5> T
@ = DB::DB called from file './xsr' line 342
  DB<5> n

Current working dir: /home/led/Letöltések/xsr (#105)Couldn't open mousegrabs: mouse will not appear in screenshots
 at ./xsr line 121.
        main::finish() called at ./xsr line 342
Current working dir: /home/led/Letöltések/xsr (#145)
Debugged program terminated.  Use q to quit or R to restart,
use o inhibit_exit to avoid stopping after program termination,
h q, h R or h o to get additional info.
  DB<5> R
Warning: some settings and command-line options may be lost!

Loading DB routines from perl5db.pl version 1.49_05
Editor support available.

Enter h or 'h h' for help, or 'man perldebug' for more help.

main::(./xsr:11):       $outfile = "Untitled Recording.html";
  DB<5> c finish
^Cmain::finish(./xsr:104):              print STDOUT "\n";
  DB<6> n

main::finish(./xsr:105):                print STDERR "Current working dir: ".cwd()." (#".__LINE__.")";
  DB<6> T
@ = DB::DB called from file './xsr' line 105
$ = main::finish('INT') called from file './xsr' line 240
$ = eval {...} called from file './xsr' line 240
  DB<6> 
```

**Comment by nonnymoose** [comment] 2017-10-09 18:16
Whoops, did not mean to close this just yet.

**Comment by nonnymoose** [comment] 2017-10-09 18:37
I'm now closing this in favor of #56

**Closed by nonnymoose** 2017-10-09 18:37 UTC
Labels: bug
